### ISSUE TITLE
Error while building gismo with gsElasticity

### ISSUE THREAD

**Issue by arastogi04** [gismo/gsElasticity#34]
Hello Developers,

I am getting the following error (in the image) while trying to compile gismo with gsElasticity. Could someone please help me sort this issue out?

Thanks!

Animesh 

![image](https://user-images.githubusercontent.com/79390857/129626808-7e171779-05a5-4fbb-a71b-eac4ac62ce45.png)

**Comment by hverhelst** [comment]
I have not seen this error recently. Probably it is resolved with some change in the base repository of [gismo](https://github.com/gismo/gismo)
